### ISSUE TITLE
Custom Icons "pico-icons"

### ISSUE THREAD

**Issue by JoseNaime** [picocss/pico#19]
### Idea
Adding minimalistic & elegant custom icons exclusive for pico to increase designers workflow, and to make it a more graceful and perfect package.

### How to?
Create a pico RestAPI to avoid any excessive downloading size, even external users could use it without downloading the pico package

**Comment by lucaslarroche** [comment]
## Icons

Icons could be a nice addition but are not exactly in the Pico spirit. Pico is more like a "Css reboot on steroids", focused on semantics HTML elements.

It seems difficult to keep an icon library minimalist and lightweight. Because there is no end. We could add hundreds of icons without being exhaustive.

I have already integrated icons for some semantic elements like `<details>`, `<input type = "date">`, `aria-invalid`, etc.

I think it's best to add an external icon library to Pico when needed for a project. For example [Feather](https://feathericons.com/), [Lucide](https://lucide.dev/), or [Octicons](https://primer.style/octicons/).

This is personally what I do for my projects.

## Customizer and RestAPI

I would like to make a customizer/generator for Pico. Like [this example](https://johann-s.github.io/bs-customizer/) for Bootstrap.
I was waiting for few more 'stars' on this repository to do so. Pico is still confidential.

In the meantime, you can create a lighter version with only the components useful to you. 
Example here: [scss/pico.slim.scss](https://github.com/picocss/pico/blob/master/scss/pico.slim.scss).

It requires recompiling Css with [Sass](https://sass-lang.com/).
