### ISSUE TITLE
Ordered list over 9 is not aligned

### ISSUE THREAD

**Issue by RCasatta** [picocss/pico#275]
Please search for duplicate or closed issues first.
  
## Describe the issue

The ordered list is not aligned when number are over 9
  
### Current Behavior

![image](https://user-images.githubusercontent.com/6470319/202034297-6b9c4883-e56d-459e-9139-921246a20434.png)

### Expected Behavior

I would expect the same alignment as with number under 10

![image](https://user-images.githubusercontent.com/6470319/202034489-430eb654-1a7f-4817-a003-46a6af686f87.png)

### Reproduction URL

https://codepen.io/RCasatta/pen/eYKEKNG

### Environment

PopOs
Firefox 106.0.1 (64-bit)

**Comment by abernh** [comment]
Picos defaults are set, so that a list <10 is properly left-aligned with the current container.

The browser defaults don't care about that alignment at all and simply set a default area for the numbers large enough to accommodate 3 digit numbers and the alignment is everywhere but not to the left so that smaller digits are showing a gap to the left border.

## Simple fix

An easy fix would be to simply increase the `padding-left` for your `<ol>` so that your highest number items are at least left aligned.

```css
ol{ padding-left: 1.6em; } // seems to fit 2 digits
```

## More sophisticated

If you want both your numbers and your texts left aligned have a look into https://stackoverflow.com/questions/10877/how-can-you-customize-the-numbers-in-an-ordered-list where different approaches are discussed but it boils down to something along side replacing the default numbering by a custom pseudo element for each list item showing a counter.

**Comment by RCasatta** [comment]
I see, thanks for the explanation
