### ISSUE TITLE
Font size in rem instead of px

### ISSUE THREAD

**Issue by kulturbande** [picocss/pico#306]
## Describe the issue

Currently the default font-size is set to 16px and it will scale up to 20px if the responsive media queries are enabled. It would be better to use `rem` instead of `px` to support people that are zooming the font sizes. I did it on my own project with Pico and I can provide a Pull Request if you would like to have these change.
  
### Current Behavior
The font - sizes are in `px`.

### Expected Behavior
The font - sizes should be in `rem`.

### Reproduction URL

[Documentation Typography](https://picocss.com/docs/typography.html)

### Environment

All browsers

### Additional Links

- [WCAG 2.1 - Resize text - Level AA](https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=131#resize-text)
- [Josh W Comeau - The Surprising Truth About Pixels and Accessibility](https://www.joshwcomeau.com/css/surprising-truth-about-pixels-and-accessibility/#accessibility-considerations-5)

**Comment by lucaslarroche** [comment]
Hi @kulturbande,

We set the root element's font size in pixels (px) and then define all the other font sizes in REMs. This way, we can easily scale all elements (padding, font size, containers, etc.) based on the base REM size.

I have a concern that the responsive scaling might not work if we use REMs for the root font size instead of pixels.

For version 2, which is currently in progress, I've been considering setting the root font size as a percentage. However, I need to do more research and testing before making a final decision.

@abernh,  I saw you had a similar comment in the [What about the Version 2?](https://github.com/picocss/pico/discussions/246#discussioncomment-4755109) discussion. What do you think would be the best solution?

**Comment by Nuc1eoN** [comment]
I'm a web designer and I've had recently a good experience using `vw` as a the root element font size.
E.g.:
```css

html {
    font-size: 1.1vw;
}

```
I don't remember where I've picked it up but it works surprisingly well, solving a lot of issues for me.

**Comment by abernh** [comment]
## font-size: 100% because a11y
I'd leave the root font size alone. There is no reason to fiddle with it.
Even worse. IF you set a base-font-size on `HTML` you override the users set browser preferences.

This is all about accessibility. The important part is how it "scales" aka "zooms" when you have different default font-sizes set for the browser.
If you left your base font-size as-is and have your layout and font-sizes based on REM your layout will scale properly and you'll always have this nice ratio between layout and font-sizes that was initially planned.

If you fiddled with it then you're ignoring the users preferences and your layout will be stuck on your predetermined base-value.
Welcome to accessibility hell.

## font-size in vw only on mobile
And regarding `html { font-size: 1.1vw; }`:  Worst. Advice. Ever. (for desktop)
@Nuc1eoN I have no idea how this ever worked for you. Not only resets this setting the default 16px for normal paragraphs to an insanely small barely readable font-size as soon as you're not in fullscreen (on desktop), but at the same time it is a ridiculous setting if you consider mobile.
Then again if you use this setting wisely on mobile you might have a winner because now, which ever the width of the users device, those paragraphs and especially titles all look exactly the same, break at the same word, etc. 
BUT again, you leave everybody who decided to have a larger default font-size "in the cold".

If you want to scale font-sizes on mobile using `vw` you might want to use a `@media` query for that along

```css
@media screen and (max-width: 768){
  h1{ font-size: calc(3vw * 3.6rem); }
}
```

## not REM but EM for more flexibility
If you are courageous you don't use REM for your font-sizes but EM.

Yes, this will mean that everything starts scaling as soon as something changes the font-size but then again maybe simply be mindful not to change your font-sizes around.

This will also allow to easily apply something like `vw`-based font-sizes on mobile on `body` level.

**Comment by Nuc1eoN** [comment]
@abernh Thank you for pointing that out!

For me it worked well, I have an auto scaling UI. On mobile I double the font-size vw factor using breakpoints. Yeah sounds ludicrous but also worth a shot for some projects.

I think we are missing the main point though. If you set root font size or not - everyone should decide for him-/herself.

However I would support the notion of using rem for everything else. Like sizing, paddings, and font-sizes.
This way the UI will scale with the users root font setting.

EM can be nice yes, but in practice I use it rarely. Mainly because often it leada to more confusion. REM has a certain clarity about it's behaviour, and that worka well.

**Comment by kulturbande** [comment]
Out of curiosity, what is the difference between 100% and 1rem for the default font size? As far as I understand the [spec](https://www.w3.org/TR/css-values-3/#font-relative-lengths) this should be the same and more common.

**Comment by Nuc1eoN** [comment]
Setting 1rem as root font size does not make sense to me. The rem value is calculated from the root element font size, so it cannot be defined in rem.
Or rather you can probably do that, but then you can just leave it out entirely.

**Comment by abernh** [comment]
> I think we are missing the main point though. If you set root font size or not - everyone should decide for him-/herself.

That's true @Nuc1eoN - everyone should decide for themselves. But who are you counting here as "everyone"?
For me it sounds more as if you are voting for "every website owner / developer / creator".

But I am talking about everyone as "every user". We are building for the users and they have to be able to use our creations. And if a user can help themself by having a larger default font-size set then I'm a happy creator if I know my setup supports that.

And if you set the root font-size you dismiss the users decision.

> I would say 100% is a good fit.
@kulturbande just dont set anything. I'm sorry if my sub-title implied that but not specifying the root font size will leave it at those 100% or 1rem or simply the default the user has set in their browser and you're fine.
