### ISSUE TITLE
hover dropdown menu no longer supported in v2?

### ISSUE THREAD

**Issue by alphatownsman** [picocss/pico#358]
Thanks for the great work on picocss and exciting v2. 
  
## Describe the issue
it seems the [hover-activated dropdown menu in v1](https://picocss.com/docs/dropdowns.html) is gone in v2

### Current Behavior
only click to open dropdown menu is supported

### Expected Behavior
restore ability to activate dropdown menu by mouse hover, or provide documentation to help achieve this

### Reproduction URL
https://v2.picocss.com/docs/dropdown

### Environment
Any

**Comment by lucaslarroche** [comment]
@alphatownsman,
Yes, it's gone:
> We also removed the experimental syntax that allowed dropdowns in the nav using nested lists.

See here:
https://picocss.com/docs/v2#breaking-changes

Because it was too hacky, and I wanted to avoid an invalid `href="#"`.

Also, the new dropdown can be used inside a nav:
https://picocss.com/docs/dropdown#usage-with-nav

Note the old docs are here:
https://picocss.com/docs/v1/dropdowns

I can reconsider it if anyone finds an elegant way to implement it.

**Comment by octoshrimpy** [comment]
I've given this a shot, @lucaslarroche. It's possible, the only caveat is having to force the details `open`. unsure how that would interact with ARIA guidelines:

https://codepen.io/octoshrimpy/pen/MYYNogM?editors=0110
