### ISSUE TITLE
Forced dark theme doesn't work on HTML elements.

### ISSUE THREAD

**Issue by igolkotek** [picocss/pico#431]
## Describe the issue
Hi

While using ready to use pico.css or sass generated pico.css I tried to set a dark theme for a `nav` element:
```css
<nav data-theme="dark">
...
</nav>
```
but the light theme remains active.
If change `header` to the dark mode - **just a color changes**.
```css
<header data-theme="dark">

```

### Current Behavior
According to the docs `Themes can be forced on document level or on any HTML element`, but `data-theme="dark"` not working on `nav` (the same is with any `ul` or `li` within `nav`, but works with `html`).

### Expected Behavior
Dark theme should work on a specific HTML element.

### Reproduction URL
[Sandbox](https://codesandbox.io/p/sandbox/lucid-blackwell-mpcd6l?file=%2Findex.html%3A14%2C20)

### Environment
Example: OS, versions, browser details.
Ubuntu 22.04
Pico v.1.5.11
Tested with Chromium, Opera, Firefox.

**Comment by igolkotek** [comment]
The same is with picocss v2

**Comment by lucaslarroche** [comment]
Yes, "...or on any HTML element" is too broad a statement.

It's true that the CSS variables impact all HTML elements, but not all HTML elements specifically define the color/background CSS properties.
And I would prefer to keep it like this. To limit the amount of CSS definitions and because most of the time, we want the backgrounds to stay transparent (if you play with backgrounds in the parent for example).

I will update the docs.

**Comment by lucaslarroche** [comment]
@igolkotek, I improved the documentation on color schemes. 
https://v2.picocss.com/docs/color-schemes

Is it better? Any suggestions?

**Comment by igolkotek** [comment]
Thank you, view it's ok. At least we know what to do with it )
