### ISSUE TITLE
Spinner not fully visible in the `<code>` element

### ISSUE THREAD

**Issue by MiroslavPetrik** [picocss/pico#469]
## Describe the issue
Using `aria-busy` with `<code>` element cuts the circle-spinner as square in bottom-right corner.  

### Current Behavior
Spinner is cut partially into square

### Expected Behavior
Spinner should be fully visible as circle

### Reproduction URL
https://codesandbox.io/p/sandbox/picocss-spinner-in-code-3y979t

### Environment
W11 & latest Chrome & Firefox

**Comment by FireIsGood** [comment]
This seems to be caused by the fact that the spinner has its width and height set as `1rem` while the background size is set as `1rem`

![image](https://github.com/picocss/pico/assets/109556932/ac46ad09-2a22-4c7d-8bf4-d269e1d73d79)

This is an issue because when the font size is changed, the spinner will resize its content box but not the actual background image of the spinner. The `<code>` element is affected since it modifies the `font-size` to be `0.875em`.

![image](https://github.com/picocss/pico/assets/109556932/f1966289-cbbd-4b61-bcc1-55f9c3b98d86)

---

One solution would be to change the `background-size` property from `1rem auto` to `1em auto:

![image](https://github.com/picocss/pico/assets/109556932/181619c8-dcf1-42c7-9331-df58af9e9ded)

If this seems correct, I can make a pull request to fix it or it could be simply changed within [pico/scss/components.scss line 18](https://github.com/picocss/pico/blob/main/scss/components/_loading.scss#L18) and rebuilt.
