### ISSUE TITLE
Fixed Aside

### ISSUE THREAD

**Issue by pspeter3** [picocss/pico#6]
Enabling a fixed width aside similar to the docs could be a good feature. Using the .grid class would make the main content and the aside the same width by default.

**Comment by lucaslarroche** [comment]
A fixed position is too specific to be added in Pico, but it can be easily added in a specific project with a single line of CSS:

```CSS
aside {
  position: fixed;
}
```
I might consider to have a better grid system in Pico.
The problem is to be able to remain minimalist and semantic.
I'm really not in favor of a _full-heavy-bulky_ [flexbox system](https://github.com/twbs/bootstrap/blob/main/dist/css/bootstrap-grid.css) like Bootstrap (+4,000 lines in this example!).

Do you have an example of a minimalist and semantic CSS grid system?

I have detailed my [opinion about grids](https://picocss.com/docs/#grids) in the documentation:

> As Pico focus on native HTML elements, we kept this grid system very minimalist.  
> A full grid system in flexbox, with all the ordering, offsetting and breakpoints utilities can be +140% of the whole Pico library size. Not really in the Pico spirit.  
> If you need a quick way to prototyping or build a complex layouts, you can look about Flexbox grid layouts. For example: Bootstrap Grid System only or Flexbox Grid.  
> If you need a light and custom grid, you can look about CSS Grid Generators. For example: CSS Grid Generator, Layoutit! or Griddy.  
> Alternatively you can Learn about CSS Grid.

**Comment by pspeter3** [comment]
I saw that opinion about grids and I agree. I think having a `.flex` helper might be sufficient, especially with `.grow`, `.shrink`, and `.normal` modifiers.

**Comment by lucaslarroche** [comment]
Unless someone suggests a minimalist and semantic grid system example, I'm still not planning to add a full grid system to Pico in the near future.

On the other hand, it would be useful to add some examples in the documentation to merge Pico with existing grid systems.

I just uploaded this example that merges and compiles Pico design system with the Bootstrap grid system.
- See it in action here: https://picocss.com/examples/bootstrap-grid/
- Source code here: https://github.com/picocss/examples/tree/dev-bootstrap-grid/bootstrap-grid

Based on this example, users could more easily understand how to compile and customize Pico with an advanced grid system.

What do you think? Should I add this example in the [documentation](https://picocss.com/docs/).

**Comment by lucaslarroche** [comment]
I published this example on the `master` branch : https://github.com/picocss/examples/tree/master/bootstrap-grid
And I added this example in docs : https://picocss.com/docs/#grids
