### ISSUE TITLE
enhancement: add issue templates

### ISSUE THREAD

**Issue by tusharnankani** [picocss/pico#89]
Hey

This is an ever-growing repository, it will keep having feature requests and PRs and the never-ending process.

We could add issue templates similar to [this](https://github.com/picocss/pico/issues/88). 
- Easy for the maintainer, not to ask for more details.
- Could ask the issue reporter for a potential fix.
- Since, we have feature_request, bug_report - we could have multiple templates.
- Including PR templates - what was fixed, issue number, any further lookouts?

Let me know, I would love to create a PR for the same.

**Comment by lucaslarroche** [comment]
Hi @tusharnankani, 

Sure, that could be an excellent addition, and I will gladly accept your help.
In Pico's minimal and inclusive spirit, I think we have to keep it short and straightforward. 
We should **suggest** a template rather than impose it. 
Pico is still small, I want nobody afraid to contribute.

**Comment by tusharnankani** [comment]
Hey @lucaslarroche 
That's a great thought, we will keep it short & simple!

**Comment by tusharnankani** [comment]
@lucaslarroche Let me know what should be done :D

**Comment by lucaslarroche** [comment]
On `dev` as I try to group the releases to avoid too many versions
