### ISSUE TITLE
Theme links

### ISSUE THREAD

**Issue by cara-tm** [picocss/pico#99]
The padding around the "Theme" links is a little excessive.

Here is some corrections:

    nav a {
        display: inline-block;
        margin: calc(var(--spacing) * -1.5) calc(var(--spacing) * -.5);
        padding: calc(var(--spacing) * .3) calc(var(--spacing) * .5) calc(var(--spacing) * .5)
    }

**Comment by lucaslarroche** [comment]
If we apply this change, we also need to edit:

```CSS
nav li { ... }
```

I don't think I will apply this suggestion because:
- We should avoid an unnecessary breaking change for Pico users,
- It's not a bug, just a style preference, and Pico is deliberately bold,
- The clickable zone would be a bit small on mobile (as everything is smaller on mobile).

One of the ideas was to use all the height for the link to have a full - bold - focus background.

![picocss com_docs_navs html(MacBookPro) (1)](https://user-images.githubusercontent.com/23470684/147844748-75ef5dc2-2848-472a-8ef9-98ceeaf12519.png)

I'm more for introducing a few more CSS vars for this component.
Ideally, all the opinionated styles should be editable with CSS vars.

**Comment by cara-tm** [comment]
Ideally, all the opinionated styles should be editable with CSS vars.

Yep!

**Comment by lucaslarroche** [comment]
After more thinking, I finally applied this suggestion.
I considered that this does not constitute a breaking change.
[Preview here](https://github.com/picocss/pico/pull/155).
